### ISSUE TITLE
[BUG]日记浏览界面无法复制

### ISSUE THREAD

**Issue by homeworkkun** [ZhuJHua/moodiary#41]
## 🐛 Bug 描述 | Bug Description

在日记浏览界面有复制按钮但无法复制文字，进入编辑界面之后才能正常复制

## 🖼️ 截图

![image](https://github.com/user-attachments/assets/fe29ed0f-27c1-4e00-8f4c-c11e4f0868a6)

##  日志内容

    Error
    2024-11-18T22:35:23.416300
    Error: PlatformException(Clipboard error, Unable to open clipboard, 5, null)
    StackTrace: #0      JSONMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:168)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334)
<asynchronous suspension>
#2      Clipboard.setData (package:flutter/src/services/clipboard.dart:36)
<asynchronous suspension>

**Comment by ZhuJHua** [comment]
Please upgrade to version 2.8.1.
